export { SupportDashboardPage } from './dashboard';
export { TicketsListPage } from './tickets-list';
export { TicketFormPage } from './ticket-form';
export { TicketDetailPage } from './ticket-detail';
export { KBListPage } from './kb-list';
export { KBFormPage } from './kb-form';
export { FAQListPage } from './faq-list';
export { FAQFormPage } from './faq-form';
export { SupportSettingsPage } from './settings';
